### ISSUE TITLE
Type declarations `.d.ts` for `rclone.js` file.

### ISSUE THREAD

**Issue by atifcppprogrammer** [sntran/rclone.js#12]
My use case requires working with typescript, consequently i require types for this module which as of now are not available.

**Comment by sntran** [comment]
Hi.

Would you be able to provide one?

**Comment by atifcppprogrammer** [comment]
@sntran Sure you can assign this issue to me

**Comment by atifcppprogrammer** [comment]
@sntran would you prefer i add the types to this package or to [DefinetlyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) ?

**Comment by atifcppprogrammer** [comment]
Sorry @sntran closed issue by mistake just now

**Comment by sntran** [comment]
No worry @atifcppprogrammer .

Since this project has no TypeScript, I think it's better suited for the types to go to the other repo. Users wanting types can install it.

**Comment by atifcppprogrammer** [comment]
@sntran Sorry for taking my time and for polluting this space with so many force pushes :sob:, the checks for the PR over at DefinitelyTyped have passed and i have added you as a co-owner for the types package, kindly please review **[that](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61173)** pull request. 

Thank you !

**Comment by sntran** [comment]
Hi there,

Sorry I could not review it in time, nor would I be able to provide much feedback on it. Thank you for your hard work getting it merged over there!

**Comment by jsejcksn** [comment]
Nice work getting the typedefs published @atifcppprogrammer
