### ISSUE TITLE
Passing IDs to rclone commands

### ISSUE THREAD

**Issue by mahsashadi** [sntran/rclone.js#13]
Hi there @sntran
Imagin I have assigned an `id` to each rclone command **log-file** executed by rclone.js in my Nodejs app.

How can I append these ids to these command to detect them in **`ps`** linux output, with below columns: 

`UID`       `PID`        `PPID`        `C`       `STIME`         `TTY`    `TIME`  `CMD` 

For example having `shadi_1234` in `UID` column or having it in a flag like `--myCustomizedId 1234` in `CMD` column.

My main purpose is to refresh application states (list of running commands along their logs), when the UI is refreshing...

**Comment by sntran** [comment]
Hi @mahsashadi !

I think this is out of the scope of `rclone.js`. This library only tries to support what the official `rclone` does. If `rclone` does not let us add extra flag, neither does `rclone.js`.
