### ISSUE TITLE
Use detached to keep child running even if its parent killed

### ISSUE THREAD

**Issue by mahsashadi** [sntran/rclone.js#14]
Hi  @sntran 

I need to keep rclone running even if its parent killed, So I need to set `detached` spawn option  `true`, But it does not work

```js
const upload = rclone.copy(srcRealPath, dstRealPath, {
              detached: true,
              'use-json-log': true,
              transfers: 100,
              'log-level' : 'INFO',
              'max-backlog': 999999,
              stats: '500ms'
            });
```

where is my mistake?

**Comment by sntran** [comment]
Hi @mahsashadi , please see notes about the `detached` option: https://nodejs.org/api/child_process.html#optionsdetached

Specifically, you need to call `unref()` on the subprocess so the parent can exit. You may also need to adjust `stdio` option.

The following example, when called with `node index.js` shows that the parent process exits, and the subprocess still runs in the background:

```js
const subprocess = rclone.copy(srcRealPath, dstRealPath, {
  detached: true,
  stdio: 'ignore',
  'use-json-log': true,
  transfers: 100,
  'log-level' : 'INFO',
  'max-backlog': 999999,
  stats: '500ms'
});

subprocess.unref();
```
