### ISSUE TITLE
Setting stdio: 'ignore' will stop event handlers working.

### ISSUE THREAD

**Issue by mahsashadi** [sntran/rclone.js#15]
Hi @sntran 

Thanks for helping in https://github.com/sntran/rclone.js/issues/14. 
As you said in that issue, I set `stdio: 'ignore'`, But none of events  (stdout, stderr, exit) work!

```js
subprocess.stdout.on('data', data => {
   // some code
});
subprocess.stderr.on('data', data => {
   // some code
});
subprocess.on('exit', (code)=>{
       code === 0 ? ws.send(JSON.stringify({type: 'complete'})) : null;
});
```
Due to [this](https://nodejs.org/api/child_process.html#optionsstdio), I think `pipe`, `overlaped`, and `inherit` values, all depends on parent, so they also won't work when the parent exits. 

So what is the solution to have events work?

**Comment by sntran** [comment]
>  I set stdio: 'ignore', But none of events (stdout, stderr, exit) work!

That is correct. You want to detach the subprocess from the parent, so the parent does not have a way to communicate to the subprocess. There is no other way that I know.

If the reason you wanted to detach the subprocess just to avoid blocking, you could just wrap it in a Promise. For example:

```js
const task = new Promise((resolve, reject) => {
  const subprocess = rclone.copy(srcRealPath, dstRealPath, {
    // some options
  });

  subprocess.stdout.on("data", (data) => {
    // some code
  });

  subprocess.stderr.on("data", (data) => {
    // some code
  });

  subprocess.on("exit", resolve);
});

task.then((code) => {
  code === 0 ? ws.send(JSON.stringify({type: 'complete'})) : null;
});
```
