### ISSUE TITLE
 Get id command rclone from ps list ubuntu in node.js

### ISSUE THREAD

**Issue by mahdi00021** [sntran/rclone.js#16]
hi
I want that get id command that rclone give to each command from ps list Ubuntu
for example:
id command is : 254544
I want get this id command from ps list in node.js

**Comment by sntran** [comment]
This is not a functionality of this library.

**Comment by sntran** [comment]
This is not a functionality of this library.

**Comment by mahdi00021** [comment]
Please help for send this id to options process ps list Ubuntu
