### ISSUE TITLE
how to send number to list process ubuntu with spawn rclone 

### ISSUE THREAD

**Issue by mahdi00021** [sntran/rclone.js#17]
i want send NUMBER_X to list process rclone 
ps -ef | grep rclone

i want see NUMBER_X in list ps -ef | grep rclone

```
const subprocess = rclone.copy(source,dest, {

  "env":{
  ...process.env,
  NUMBER_X:1234
  },
  detached: true,
  
  'use-json-log': true,
  transfers: 100,
  'log-level' : 'INFO',
  'max-backlog': 999999,
  stats: '500ms',
 
});
```

**Comment by sntran** [comment]
This `rclone.js` library only spawns rclone process and passes arguments to it. What and how you handle arguments are up to the user. How to do a certain requirement with the subprocess is out of scope of this library.

**Comment by mahdi00021** [comment]
@sntran 
How do i pass passes arguments to it?
