### ISSUE TITLE
 How do I pass arguments OR Custom option to process rclone?

### ISSUE THREAD

**Issue by mahdi00021** [sntran/rclone.js#18]
How do I pass arguments OR Custom option to process rclone?

```
const subprocess = rclone.copy(source,dest, {

  "env":{
  ...process.env,
  NUMBER_X:1234
  },
  detached: true,
  
  'use-json-log': true,
  transfers: 100,
  'log-level' : 'INFO',
  'max-backlog': 999999,
  stats: '500ms',
 
});
```

**Comment by sntran** [comment]
Besides [child options](https://nodejs.org/api/child_process.html#child_processspawncommand-args-options) and `rclone`'s, you can't add custom argument.

Again, this library is just a wrapper to `rclone`.

**Comment by mahdi00021** [comment]
@sntran my question is about rclone

**Comment by sntran** [comment]
And I did answer you. You can't pass custom argument.
