### ISSUE TITLE
File transfer progress

### ISSUE THREAD

**Issue by timuster** [sntran/rclone.js#2]
Is there a way to see the progress when copying files to a remote destination?

A callback function that's called every N seconds (or on progress) would be helpful when backing up large files.

**Comment by sntran** [comment]
Technically, most calls returns a `ReadableStream`, so you can just listen to its `stdout` and `stderr` on "data" event to keep track of the progress.

```js
const rclone = require("rclone.js");

const upload = rclone.copy("source:", "-P");

upload.stdout.on("data", (data) => {
  console.log(data.toString());
});

upload.stderr.on("data", (data) => {
  console.error(data.toString());
});
```

Can't you get the progress data from there?

**Comment by mahsashadi** [comment]
@sntran 
the `data` shown in `stderr` is rclone logs, something like:
```
2022/06/11 09:44:06 INFO  : f3: Copied (new)
2022/06/11 09:44:06 INFO  : f1: Copied (new)
2022/06/11 09:44:07 INFO  : 
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:            9 / 9, 100%
Elapsed time:         0.3s
```

But to show progress, I need some `percentage data`

**Comment by viperadnan-git** [comment]
> @sntran the `data` shown in `stderr` is rclone logs, something like:
> 
> ```
> 2022/06/11 09:44:06 INFO  : f3: Copied (new)
> 2022/06/11 09:44:06 INFO  : f1: Copied (new)
> 2022/06/11 09:44:07 INFO  : 
> Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
> Transferred:            9 / 9, 100%
> Elapsed time:         0.3s
> ```
> 
> But to show progress, I need some `percentage data`

Try using `-v --use-json-log --stats 1s`, you will get json output on stderr
