### ISSUE TITLE
Add ability to pass options to child process spawned (e.g. env vars)

### ISSUE THREAD

**Issue by niftylettuce** [sntran/rclone.js#4]
https://nodejs.org/api/child_process.html#child_processspawncommand-args-options

**Comment by sntran** [comment]
Hi there,

This was addressed in https://github.com/sntran/rclone.js/commit/c6c57e14f0a6d14caf99a363497774408ea43d3f. Can you give it a try?

**Comment by niftylettuce** [comment]
Ah this is clever, could this be added to the docs perhaps?  Maybe an example with `env`, since rclone allows you to pass env vars in the command.

https://rclone.org/docs/#environment-variables

**Comment by sntran** [comment]
Technically, `env` option defaults to `process.env`, so you can already use rclone's environment variables directly in the shell.

For example:

```shell
RCLONE_CONFIG=~/.config/rclone/rclone.conf npx rclone ls source:
```

I can't remember if I did test that or not :) If you can give it a try, let me know what you find.

I'll find some time to try that and update the docs.

**Comment by niftylettuce** [comment]
I wanted to do this in a sandboxed way, that way only the child process would have the env vars, so that's why I wanted to see if spawn support was there for it - which it is.
