### ISSUE TITLE
Error on npm install of 0.6.0

### ISSUE THREAD

**Issue by bmckinney** [sntran/rclone.js#5]
$ npm install rclone.js

> rclone.js@0.6.0 postinstall C:\Users\*******\projects\*********\node_modules\rclone.js
> node bin/rclone.js selfupdate

C:\Users\******\projects\*******\node_modules\rclone.js\bin\rclone.js:35
subprocess.stdout?.on("data", (data) => {
                  ^

**Comment by sntran** [comment]
Thanks for reporting! Would you mind giving me more of the stacktrace?

And also your node version please?
