### ISSUE TITLE
Can't do keyboard inputs using the CLI

### ISSUE THREAD

**Issue by xarunoba** [sntran/rclone.js#6]
Hello! This is a pretty useful wrapper but I have encountered an issue:
I wanted to try making an rclone config using the CLI command but it cannot trigger any keyboard inputs.
I've tried it in 3 different Windows terminals: Git Bash, PowerShell, & CMD.

I made a roundabout fix and generated my own config file using the actual rclone CLI and imported it in the wrapper CLI's config.
NPX: `npx rclone --config=rclone.conf`
PNPM: `pnpm exec rclone --config=rclone.conf`

Here's some information that might help:
```
node v14.17.3
rclone v1.58.0
- os/version: Microsoft Windows 10 Home Single Language 20H2 (64 bit)
- os/kernel: 10.0.19042.1586 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.17.8
- go/linking: dynamic
- go/tags: cmount
```

Thank you for your work,
@Xarunoba

**Comment by sntran** [comment]
Thanks to @Xarunoba, this has been resolved and published to v0.6.5
