### ISSUE TITLE
Not enter in stdout.on block

### ISSUE THREAD

**Issue by mahsashadi** [sntran/rclone.js#8]
HI :)
Although the `copy` action is done correctly, why it did not enter `stdout.on` block? 
I need to send copy progress (percentage) to client. What should I do?
```js

    const rclone = require('rclone.js');

    const copy = rclone.copy('example/src/path', 'example/dst/path', {
           verbose : true
    });
    copy.stdout.on('data', (data) => {
          console.log('Entered in this block');
    });
```

server logs:

```
2022/05/07 18:45:55 INFO  : file1: Copied (new)

2022/05/07 18:45:55 INFO  : file2: Copied (new)

2022/05/07 18:45:55 INFO  : file3: Copied (new)

2022/05/07 18:45:56 INFO  : file4: Copied (new)

2022/05/07 18:45:58 INFO  : file5: Copied (new)

2022/05/07 18:45:58 INFO  : 
Transferred:        6.848 MiB / 6.848 MiB, 100%, 2.785 MiB/s, ETA 0s
Transferred:            5 / 5, 100%
Elapsed time:         2.8s
```

**Comment by mahsashadi** [comment]
Thank You Beforehand @Xarunoba @sntran

**Comment by sntran** [comment]
I believe rclone sends progress to `stderr` instead of `stdout`.

**Comment by mahsashadi** [comment]
> I believe rclone sends progress to `stderr` instead of `stdout`.

Oh! I expect to have errors in `stderr`!
So since the output is in `buffer` format, should I convert it to `string` and process the string to extract items like filenames, elapsed-time and etc.?
@sntran

**Comment by sntran** [comment]
Sorry for the late response.

>  I expect to have errors in stderr!

This is somewhat a convention, since `stdout` can be used to actually output data, such as `ls` and such. Therefore, progress and/or other information are usually sent to `stderr`.

> So since the output is in buffer format, should I convert it to string and process the string to extract items like filenames, elapsed-time and etc.?

That's correct. I would also suggest `--stats-one-line` flag to have a simpler progress line for easier parsing.
